import os

replacements_home = {
    "Tim kiem trai cay, rau cu...": "Tìm kiếm trái cây, rau củ...",
    ">Trang Chu<": ">Trang Chủ<",
    ">Trai Cay<": ">Trái Cây<",
    ">Rau Cu<": ">Rau Củ<",
    ">Nhap Khau<": ">Nhập Khẩu<",
    ">Khuyen Mai<": ">Khuyến Mãi<",
    "title=\"Thong bao\"": "title=\"Thông báo\"",
    "title=\"Gio hang\"": "title=\"Giỏ hàng\"",
    "San Pham Hot Nhat": "Sản Phẩm Hot Nhất",
    "Trai Cay<br>Nhap Khau Cao Cap": "Trái Cây<br>Nhập Khẩu Cao Cấp",
    "Chon loc tu nhung vuon cay tot nhat the gioi.<br>Giao tan tay trong ngay.": "Chọn lọc từ những vườn cây tốt nhất thế giới.<br>Giao tận tay trong ngày.",
    "Mua Ngay": "Mua Ngay",
    "Xem Tat Ca": "Xem Tất Cả",
    "Giam Gia Den 30%": "Giảm Giá Đến 30%",
    "Trai Cay<br>Huu Co Sach": "Trái Cây<br>Hữu Cơ Sạch",
    "Trong theo tieu chuan huu co quoc te.<br>An toan cho ca gia dinh.": "Trồng theo tiêu chuẩn hữu cơ quốc tế.<br>An toàn cho cả gia đình.",
    "Kham Pha": "Khám Phá",
    "Uu Dai Hom Nay": "Ưu Đãi Hôm Nay",
    "Dac San Mien Nam": "Đặc Sản Miền Nam",
    "Trai Cay<br>Noi Dia Tuoi Ngon": "Trái Cây<br>Nội Địa Tươi Ngon",
    "Thang nay: Xoai cat Hoa Loc, Sau rieng, Mit.<br>Thom ngon dung mua.": "Tháng này: Xoài cát Hòa Lộc, Sầu riêng, Mít.<br>Thơm ngon đúng mùa.",
    "Dat Hang": "Đặt Hàng",
    "Xem Bo Suu Tap": "Xem Bộ Sưu Tập",
    "Mien Phi Van Chuyen": "Miễn Phí Vận Chuyển",
    "Don hang tu 200.000 VND tro len": "Đơn hàng từ 200.000 VNĐ trở lên",
    "Chat Luong Dam Bao": "Chất Lượng Đảm Bảo",
    "Kiem tra 100% truoc khi giao hang": "Kiểm tra 100% trước khi giao hàng",
    "Doi Tra De Dang": "Đổi Trả Dễ Dàng",
    "Hoan tien 100% neu san pham hong": "Hoàn tiền 100% nếu sản phẩm hỏng",
    "Danh Muc San Pham": "Danh Mục Sản Phẩm",
    "Xem tat ca": "Xem tất cả",
    "Trai Cay Nhap Khau": "Trái Cây Nhập Khẩu",
    "san pham": "sản phẩm",
    "Trai Cay Noi Dia": "Trái Cây Nội Địa",
    "Trai Cay Huu Co": "Trái Cây Hữu Cơ",
    "Trai Cay Cao Cap": "Trái Cây Cao Cấp",
    "San Pham Noi Bat": "Sản Phẩm Nổi Bật",
    "Bo Suu Tap Dac Biet Thang Nay": "Bộ Sưu Tập Đặc Biệt Tháng Này",
    "Nhung san pham duoc lua chon thu cong boi doi ngu chuyen gia": "Những sản phẩm được lựa chọn thủ công bởi đội ngũ chuyên gia",
    "Tat Ca San Pham": "Tất Cả Sản Phẩm",
    "Xem them": "Xem thêm",
    "Danh Muc<": "Danh Mục<",
    "Khoang Gia": "Khoảng Giá",
    "Tu 0": "Từ 0",
    "Den 500k": "Đến 500k",
    "Ap Dung": "Áp Dụng",
    "Danh Gia": "Đánh Giá",
    "(5 sao)": "(5 sao)",
    "tro len": "trở lên",
    "Tinh Trang": "Tình Trạng",
    ">Con Hang<": ">Còn Hàng<",
    ">Het Hang<": ">Hết Hàng<",
    "Hien thi": "Hiển thị",
    "Sap xep:": "Sắp xếp:",
    "Pho Bien": "Phổ Biến",
    "Moi Nhat": "Mới Nhất",
    "Gia Tang": "Giá Tăng",
    "Gia Giam": "Giá Giảm",
    ">Moi<": ">Mới<",
    "Tao My Fuji Tuoi Gion": "Táo Mỹ Fuji Tươi Giòn",
    "Nho Uc Khong Hat Tuoi": "Nho Úc Không Hạt Tươi",
    "Xoai Cat Hoa Loc Dac San": "Xoài Cát Hòa Lộc Đặc Sản",
    "Cam Huu Co Da Lat Tuoi": "Cam Hữu Cơ Đà Lạt Tươi",
    "Dao My Vang Gion Ngot": "Đào Mỹ Vàng Giòn Ngọt",
    "Sau Rieng Musang King": "Sầu Riêng Musang King",
    ">Con ": ">Còn ",
    "Them<": "Thêm<",
    ">Het<": ">Hết<",
    "Het hang": "Hết hàng",
    "Ban Chay Nhat": "Bán Chạy Nhất",
    "Ban: ": "Bán: ",
    "Bai Viet Noi Bat": "Bài Viết Nổi Bật",
    "Suc Khoe": "Sức Khỏe",
    "5 Loai Trai Cay Tot Nhat Cho Suc Khoe": "5 Loại Trái Cây Tốt Nhất Cho Sức Khỏe",
    "Kham pha nhung loai trai cay bo duong nhat ban nen an moi ngay de tang cuong suc de khang va nang luong.": "Khám phá những loại trái cây bổ dưỡng nhất bạn nên ăn mỗi ngày để tăng cường sức đề kháng và năng lượng.",
    "luot xem": "lượt xem",
    "Meo Hay": "Mẹo Hay",
    "Huong Dan Bao Quan Trai Cay Dung Cach": "Hướng Dẫn Bảo Quản Trái Cây Đúng Cách",
    "Meo hay de giu trai cay tuoi lau hon trong tu lanh va nhiet do phong, giup tiet kiem chi phi mua sam.": "Mẹo hay để giữ trái cây tươi lâu hơn trong tủ lạnh và nhiệt độ phòng, giúp tiết kiệm chi phí mua sắm.",
    "Kien Thuc": "Kiến Thức",
    "Phan Biet Trai Cay Huu Co Va Thuong Thuong": "Phân Biệt Trái Cây Hữu Cơ Và Thông Thường",
    "Nhung diem khac biet quan trong giup ban chon duoc san pham huu co that su, an toan cho gia dinh.": "Những điểm khác biệt quan trọng giúp bạn chọn được sản phẩm hữu cơ thực sự, an toàn cho gia đình.",
    "Chuyen cung cap trai cay tuoi ngon, chat luong cao tu cac vuon trong uy tin trong nuoc va quoc te. Giao hang tan noi, uy tin hang dau.": "Chuyên cung cấp trái cây tươi ngon, chất lượng cao từ các vườn trồng uy tín trong nước và quốc tế. Giao hàng tận nơi, uy tín hàng đầu.",
    "Ho Tro<": "Hỗ Trợ<",
    "Chinh Sach Doi Tra": "Chính Sách Đổi Trả",
    "Chinh Sach Giao Hang": "Chính Sách Giao Hàng",
    "Huong Dan Dat Hang": "Hướng Dẫn Đặt Hàng",
    "Cau Hoi Thuong Gap": "Câu Hỏi Thường Gặp",
    "Lien He<": "Liên Hệ<",
    "Trai cay tuoi ngon moi ngay.": "Trái cây tươi ngon mỗi ngày.",
    "Ho So Cua Toi": "Hồ Sơ Của Tôi",
    "Bao Mat": "Bảo Mật",
    "Dang Xuat": "Đăng Xuất",
    "Sena Shop - Trai Cay Tuoi Ngon Moi Ngay": "Sena Shop - Trái Cây Tươi Ngon Mỗi Ngày"
}

replacements_profile = {
    "Ho So Ca Nhan": "Hồ Sơ Cá Nhân",
    "Quan Tri Vien": "Quản Trị Viên",
    "Nhan Vien Ban Hang": "Nhân Viên Bán Hàng",
    "Nhan Vien Giao Hang": "Nhân Viên Giao Hàng",
    "Chua cap nhat": "Chưa cập nhật",
    ">Nam<": ">Nam<",
    ">Nu<": ">Nữ<",
    "Ho so cua toi": "Hồ sơ của tôi",
    "Quan ly thong tin ca nhan": "Quản lý thông tin cá nhân",
    "Thong tin ca nhan": "Thông tin cá nhân",
    "Ho ten": "Họ tên",
    "So dien thoai": "Số điện thoại",
    "Gioi tinh": "Giới tính",
    "Ngay tham gia": "Ngày tham gia",
    "Dia chi giao hang mac dinh": "Địa chỉ giao hàng mặc định",
    "Luu Thay Doi": "Lưu Thay Đổi",
    "Doi Mat Khau": "Đổi Mật Khẩu",
    "De bao mat tai khoan, vui long khong chia se mat khau cho nguoi khac": "Để bảo mật tài khoản, vui lòng không chia sẻ mật khẩu cho người khác",
    "Mat khau hien tai": "Mật khẩu hiện tại",
    "Mat khau moi": "Mật khẩu mới",
    "Xac nhan mat khau moi": "Xác nhận mật khẩu mới",
    "Cap Nhat Mat Khau": "Cập Nhật Mật Khẩu",
    "Tim kiem trai cay, rau cu...": "Tìm kiếm trái cây, rau củ...",
    ">Trang Chu<": ">Trang Chủ<",
    ">Trai Cay<": ">Trái Cây<",
    ">Rau Cu<": ">Rau Củ<",
    ">Nhap Khau<": ">Nhập Khẩu<",
    ">Khuyen Mai<": ">Khuyến Mãi<",
    "Ho So Cua Toi": "Hồ Sơ Của Tôi",
    "Bao Mat": "Bảo Mật",
    "Dang Xuat": "Đăng Xuất",
    "Trai cay tuoi ngon moi ngay.": "Trái cây tươi ngon mỗi ngày.",
    "Chinh Sach Doi Tra": "Chính Sách Đổi Trả",
    "Chinh Sach Giao Hang": "Chính Sách Giao Hàng",
    "Huong Dan Dat Hang": "Hướng Dẫn Đặt Hàng",
    "Cau Hoi Thuong Gap": "Câu Hỏi Thường Gặp",
    "Ho Tro<": "Hỗ Trợ<",
    "Lien He<": "Liên Hệ<"
}

def apply_replacements(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    for old, new in replacements.items():
        content = content.replace(old, new)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

apply_replacements(r'f:\SWP391\PROJECT\SWP391_SUM26\web\home.html', replacements_home)
apply_replacements(r'f:\SWP391\PROJECT\SWP391_SUM26\web\profile.jsp', replacements_profile)

print("Done replacements")
